### ISSUE TITLE
src/Defaults.php detected as a virus

### ISSUE THREAD

**Issue by scottconnerly** [rollbar/rollbar-php#269]
Avast is classifying it as "PHP:Agent-BP [Trj]".  My guess is because of the exec() calls, but I don't really know.

**Comment by jessewgibbs** [comment]
Hey Scott,

Thanks for the info.  Is the misidentification of this file as a virus causing rollbar-php to not work properly?  I'm not familiar w/ how Avast handles PHP files it believes contain a virus...

**Comment by scottconnerly** [comment]
Yes, it moves the file to a quarantine area.

**Comment by jessewgibbs** [comment]
Is it possible to whitelist this file in Avast so that it doesn't get quarantined?  It may take us a while to investigate this, and I want to get your rollbar-php up and running again as fast as possible...

**Comment by scottconnerly** [comment]
Yes, we're able to function.

**Comment by jessewgibbs** [comment]
Unfortunately I can't find any information on what Avast scans for in PHP files so we'd need to install Avast and run it in order to identify whether any changes we make would work.

**Comment by ArturMoczulski** [comment]
The process of whitelisting applications is explained in detail here:
https://www.avast.com/faq.php?article=AVKB228
https://www.avast.com/faq.php?article=AVKB229

I reached out to Avast Threat Lab to get `src/Defaults.php` whitelisted. I will update as they come back to me.

**Comment by ArturMoczulski** [comment]
Avast Threat Lab has added `src/Defaults.php` to the whitelist almost immediately. Can you please check if you're still running into issues with this?

**Comment by scottconnerly** [comment]
Since I told my installation of Avast the file was OK, I don't see a way to un-do that. It'd have to be somebody else who tests it.

**Comment by ArturMoczulski** [comment]
Ok. I'm assuming this is fixed then.

**Comment by tbopec** [comment]
Hello, @ArturMoczulski 

I just downloaded and installed the latest version of Avast.
It still blocks src/Defaults.php and put in into chest.

So, it's not fixed. Do you know, when Avast should release new whitelisting? Or how should it be resolved?

Do you have an idea, which part of code is responsible for the virus detection?

Best regards,
Pavel
